language: generic
# below line is because to use docker u need super-user permissions
sudo: required 
services:
    - docker

before_install:
    - docker build -t mduliszewski/docker-react -f Dockerfile.dev .
 
script:
    - docker run -e CI=true mduliszewski/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-681757544358"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY